-- Run this once in Supabase Dashboard > SQL Editor.
create table if not exists public.discipline_missions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_day date not null,
  mission_index integer not null check (mission_index between 0 and 89),
  mission_text text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, mission_day)
);

alter table public.discipline_missions enable row level security;

create policy "Users can view their own discipline missions"
on public.discipline_missions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own discipline missions"
on public.discipline_missions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own discipline missions"
on public.discipline_missions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
